### ISSUE TITLE
Help users find what projects to start with - Interactive Page

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Call-for-Code-for-Racial-Justice#8]
## Goal:

Create an interactive experience that makes it easier for visitors to know which projects fit their programming experience and interest so that they can get started.  

## Background:

It is currently hard for new users to know how to get started. It's also difficult to match new users to 

## User Journey
- allows visitors to input their preferences: preferring programming language, desired level of contribution, mobile/web, front end/back end, non-development opportunities

- [x] v1. website returns the CFCFRJ projects that match the user's preference
- [ ] v2. website also returns the github issues that match the user's preference
- [ ] v3. website returns to programming languages close to user's preference. 
- [ ] v4. website also returns the architecture component that is built 

---

# Tasks:

- Design workshop/thinking 
- Data object defining
- Tech meeting and pre-reqs set up; (JSON). 
- UI mockup & Github Page exploration 
- Make page dynamic

# Requirements

MVP V1:
- JSON data object using[ IBM Cloudant](https://www.ibm.com/cloud/cloudant)
- Website built on [Github Pages ](https://pages.github.com/)
- database of: role, project, language, component type: mobile/web, front end/ back end
- Github API (maybe v2) integration
- Interactive &  dynamic UI and nice visualization
- Project Object: Project description for each returned project & relevant links. 
- Filter capability on UI
<img width="1055" alt="Screen Shot 2021-07-01 at 9 59 13 AM" src="https://media.github.ibm.com/user/252027/files/658d1500-da6c-11eb-82da-375fea58b929">

- [ Mural Mockup ](https://app.mural.co/invitation/mural/callforcodeforracialjustice6756/1624475558910?sender=demiajayi4769&key=10cba60d-2540-4c42-b288-517b323c76ff)
V2 of Page
- filter Github issues by label
- create bug hunter/good first issue view and UI

## Acceptance Criteria MVP 1: 

- As a user I'm able to input my programming language and get back recommendations of relevant projects to look at.
- As a user I can find projects I can get started on within 5 minutes of joining Call for Code for Racial Justice
- As a user I am able to see the programming languages the project uses. 
- As a user I am also to see projects by front end/back end
- As a non-technical user I'm confident and aware of the ways I can get started
- As a user in a different country with bandwidth restrictions I am able to navigate the site without any issues

## How this helps us meet our Objectives:
